"""Photoreal Isaac-Sim hero render of the Conet Tactile inspection line.

Single source of truth for the marketing / handoff hero shots. Built from
``sim/specs.py`` (real dimensions) plus three on-disk authorities:

* the printable enclosure CAD at ``hardware/edge_enclosure/edge_enclosure.scad``
  → exported through OpenSCAD into STL → imported as a vertex-smoothed USD
  mesh so the chamfered bezel, the vent grille, the VESA pocket all read
  correctly (no hand-modelled stand-in cube).
* the procedural PBR texture set generated by ``sim.isaac.textures`` —
  concrete sweep, PU rubber belt, brushed anodized aluminium, polished
  stainless, Velostat fabric, green PCB solder mask, pharma white. Every
  big surface in the scene binds to one of those (diffuse + roughness +
  normal) so RTX path-traces real reflections / micro-shadows, not flat
  swatches.
* the factory HDRI at ``$SCENE_HDRI`` (default ``/workspace/hdri.hdr``).
  We add a **curved cyclorama** sweep behind everything so the polished
  concrete floor seamlessly bends up into the dome — no horizon line, no
  "floor stops here and HDRI starts" jump.

Geometry highlights:

* belt is one continuous loop that wraps around two end rollers
* rollers carry stainless end caps + bearing housings + a side drive motor
* frame is 40 mm T-slot aluminium extrusion (verticals, longitudinals,
  cross-braces, levelling feet)
* mesh sensor is a subdivided Velostat strip + a 10 mm cell grid + an FFC
  ribbon down to the scanner PCB
* the Tactile Edge kiosk is *only* the printed body+bezel from the .scad,
  with a recessed emissive 7" display and a detailed Jetson Orin Nano
  (finned heatsink + fan + GPIO header) sitting inside

Run on the GPU pod:

    OMNI_KIT_ACCEPT_EULA=YES python sim/isaac/scene.py

Outputs ``sim/isaac/out/twin_scene.png`` / ``twin_overview.png`` /
``twin_line.png`` (1600×1000, path-traced).
"""
from __future__ import annotations

import math
import os
import shutil
import struct
import subprocess

from isaacsim import SimulationApp

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(HERE, "out")
ASSETS = os.path.join(HERE, "assets")
os.makedirs(OUT, exist_ok=True)
os.makedirs(ASSETS, exist_ok=True)

_W, _H = 1600, 1000
sim_app = SimulationApp(
    {"headless": True, "renderer": "RayTracedLighting", "width": _W, "height": _H}
)

import sys  # noqa: E402 — required before SimulationApp-dependant imports

sys.path.insert(0, REPO)
import numpy as np  # noqa: E402
import omni.replicator.core as rep  # noqa: E402
from PIL import Image  # noqa: E402
from pxr import Gf, Sdf, UsdGeom, UsdLux, UsdShade  # noqa: E402

import sim.specs as S  # noqa: E402
from sim.isaac import textures as TEX  # noqa: E402


# ── world scale ────────────────────────────────────────────────────────────

BELT_LEN    = 2.40                       # full line section (longer than the bench spec)
MESH_BELT_W = 0.30                       # tactile mat width (inside the rails)
BELT_TOP    = -S.MESH_THICK              # belt top run, just under the mat
ROLLER_R    = S.ROLLER_DIA / 2
BELT_BOT    = BELT_TOP - 2 * ROLLER_R    # bottom (return) run
FLOOR_Z     = -0.36                      # factory floor
HX, HY      = BELT_LEN / 2, S.BELT_WIDTH / 2


# ── helpers ────────────────────────────────────────────────────────────────

def _xform(prim, pos=None, euler=None, scale=None):
    xf = UsdGeom.Xformable(prim)
    if pos is not None:
        xf.AddTranslateOp().Set(Gf.Vec3d(*pos))
    if euler is not None:
        xf.AddRotateXYZOp().Set(Gf.Vec3f(*euler))
    if scale is not None:
        xf.AddScaleOp().Set(Gf.Vec3f(*scale))


def _bind(prim, mat):
    UsdShade.MaterialBindingAPI.Apply(prim).Bind(mat)


def _box(stage, path, dims, pos, mat, euler=None):
    c = UsdGeom.Cube.Define(stage, path)
    c.CreateSizeAttr(1.0)
    _xform(c.GetPrim(), pos, euler, tuple(dims))
    _bind(c.GetPrim(), mat)
    return c


def _cyl(stage, path, radius, height, pos, mat, axis="Z", euler=None):
    c = UsdGeom.Cylinder.Define(stage, path)
    c.CreateRadiusAttr(radius)
    c.CreateHeightAttr(height)
    c.CreateAxisAttr(axis)
    _xform(c.GetPrim(), pos, euler)
    _bind(c.GetPrim(), mat)
    return c


def _capsule(stage, path, radius, height, pos, mat, axis="Z", euler=None, scale=None):
    c = UsdGeom.Capsule.Define(stage, path)
    c.CreateRadiusAttr(radius)
    c.CreateHeightAttr(height)
    c.CreateAxisAttr(axis)
    _xform(c.GetPrim(), pos, euler, scale)
    _bind(c.GetPrim(), mat)
    return c


def _sphere(stage, path, radius, pos, mat, scale=None):
    s = UsdGeom.Sphere.Define(stage, path)
    s.CreateRadiusAttr(radius)
    _xform(s.GetPrim(), pos, None, scale)
    _bind(s.GetPrim(), mat)
    return s


def _mesh(stage, path, points, face_indices, face_counts, mat, *,
          pos=None, euler=None, scale=None, normals=None, st=None,
          smooth=True):
    """Generic USD mesh with optional smooth vertex normals + UVs."""
    m = UsdGeom.Mesh.Define(stage, path)
    m.CreatePointsAttr([Gf.Vec3f(float(p[0]), float(p[1]), float(p[2])) for p in points])
    m.CreateFaceVertexIndicesAttr([int(i) for i in face_indices])
    m.CreateFaceVertexCountsAttr([int(c) for c in face_counts])
    m.CreateSubdivisionSchemeAttr(UsdGeom.Tokens.none)
    if normals is not None:
        m.CreateNormalsAttr(
            [Gf.Vec3f(float(n[0]), float(n[1]), float(n[2])) for n in normals])
        m.SetNormalsInterpolation(UsdGeom.Tokens.vertex)
    if st is not None:
        pv = UsdGeom.PrimvarsAPI(m.GetPrim()).CreatePrimvar(
            "st", Sdf.ValueTypeNames.TexCoord2fArray,
            interpolation=UsdGeom.Tokens.vertex)
        pv.Set([Gf.Vec2f(float(uv[0]), float(uv[1])) for uv in st])
    if smooth and normals is None:
        # USD treats `none` subdiv + missing normals as flat shading; turn on
        # `catmullClark` only if the caller didn't supply geometry-correct normals.
        pass
    _xform(m.GetPrim(), pos, euler, scale)
    _bind(m.GetPrim(), mat)
    return m


# ── materials (OmniPBR/MDL with textures) ──────────────────────────────────

def _omnipbr(stage, path, *, diffuse=None, diffuse_tex=None, rough=0.5,
             rough_tex=None, normal_tex=None, metallic=0.0, metallic_tex=None,
             specular=0.5, emissive=None, emit=0.0, project_uvw=True,
             tex_scale=1.0):
    """Real OmniPBR material — metals reflect the HDRI, textures bind into the
    MDL inputs so concrete / brushed alu / Velostat actually catch the light.
    Pass either `diffuse` (Gf.Vec3) or `diffuse_tex` (filesystem path)."""
    mat = UsdShade.Material.Define(stage, path)
    sh = UsdShade.Shader.Define(stage, path + "/Shader")
    sh.SetSourceAsset("OmniPBR.mdl", "mdl")
    sh.SetSourceAssetSubIdentifier("OmniPBR", "mdl")

    def fset(name, vtype, val):
        sh.CreateInput(name, vtype).Set(val)

    def aset(name, path_):
        sh.CreateInput(name, Sdf.ValueTypeNames.Asset).Set(Sdf.AssetPath(path_))

    if diffuse_tex is not None:
        aset("diffuse_texture", diffuse_tex)
    if diffuse is not None:
        fset("diffuse_color_constant", Sdf.ValueTypeNames.Color3f, Gf.Vec3f(*diffuse))
    fset("metallic_constant", Sdf.ValueTypeNames.Float, float(metallic))
    if metallic_tex is not None:
        aset("metallic_texture", metallic_tex)
        fset("metallic_texture_influence", Sdf.ValueTypeNames.Float, 1.0)
    fset("reflection_roughness_constant", Sdf.ValueTypeNames.Float, float(rough))
    if rough_tex is not None:
        aset("reflectionroughness_texture", rough_tex)
        fset("reflection_roughness_texture_influence", Sdf.ValueTypeNames.Float, 1.0)
    if normal_tex is not None:
        aset("normalmap_texture", normal_tex)
        fset("flip_tangent_v", Sdf.ValueTypeNames.Bool, False)
    fset("specular_level", Sdf.ValueTypeNames.Float, float(specular))
    if project_uvw:
        fset("project_uvw", Sdf.ValueTypeNames.Bool, True)
        fset("texture_scale", Sdf.ValueTypeNames.Float2,
             Gf.Vec2f(tex_scale, tex_scale))
    if emissive is not None:
        fset("enable_emission", Sdf.ValueTypeNames.Bool, True)
        fset("emissive_color", Sdf.ValueTypeNames.Color3f, Gf.Vec3f(*emissive))
        fset("emissive_intensity", Sdf.ValueTypeNames.Float, float(emit))
    mat.CreateSurfaceOutput("mdl").ConnectToSource(sh.ConnectableAPI(), "out")
    return mat


def build_materials(stage, root, tex):
    def P(name, **kw):
        return _omnipbr(stage, f"{root}/M/" + name, **kw)
    return dict(
        # background sweep / floor — projected so the texture tiles across the curve
        concrete=P("concrete", diffuse_tex=tex["concrete"]["diffuse"],
                   rough_tex=tex["concrete"]["rough"],
                   normal_tex=tex["concrete"]["normal"],
                   rough=0.42, specular=0.45, tex_scale=4.0),
        # food-grade dark PU belt
        belt=P("belt", diffuse_tex=tex["belt"]["diffuse"],
               rough_tex=tex["belt"]["rough"],
               normal_tex=tex["belt"]["normal"],
               rough=0.55, specular=0.35, tex_scale=8.0),
        # anodized aluminium for the frame, rails, kiosk bezel
        alu=P("alu", diffuse_tex=tex["alu"]["diffuse"],
              rough_tex=tex["alu"]["rough"],
              normal_tex=tex["alu"]["normal"],
              metallic=1.0, rough=0.24, specular=0.85, tex_scale=6.0),
        # polished stainless for rollers, rails, hardware
        steel=P("steel", diffuse_tex=tex["steel"]["diffuse"],
                rough_tex=tex["steel"]["rough"],
                normal_tex=tex["steel"]["normal"],
                metallic=1.0, rough=0.16, specular=0.95, tex_scale=4.0),
        # Velostat tactile film
        velostat=P("velostat", diffuse_tex=tex["velostat"]["diffuse"],
                   rough_tex=tex["velostat"]["rough"],
                   normal_tex=tex["velostat"]["normal"],
                   rough=0.5, specular=0.5, tex_scale=10.0),
        # 3D-printed PETG graphite (kiosk body)
        graphite=P("graphite", diffuse_tex=tex["graphite"]["diffuse"],
                   rough_tex=tex["graphite"]["rough"],
                   normal_tex=tex["graphite"]["normal"],
                   metallic=0.0, rough=0.55, specular=0.4, tex_scale=4.0),
        # green PCB solder mask (scanner board + Jetson carrier)
        pcb=P("pcb", diffuse_tex=tex["pcb"]["diffuse"],
              rough_tex=tex["pcb"]["rough"],
              normal_tex=tex["pcb"]["normal"],
              rough=0.4, specular=0.45, tex_scale=2.0),
        # solid colours for tiny details
        # the printed 10 mm cell grid lines on the velostat: deliberately subtle
        # (real velostat shows the cells only as a faint dye on the mat surface)
        cell=P("cell", diffuse=(0.04, 0.07, 0.06), rough=0.7, specular=0.18,
               project_uvw=False),
        chip=P("chip", diffuse=(0.05, 0.05, 0.06), metallic=0.3,
               rough=0.45, specular=0.55, project_uvw=False),
        conn=P("conn", diffuse=(0.86, 0.87, 0.89), metallic=0.9, rough=0.3,
               specular=0.9, project_uvw=False),
        ffc=P("ffc", diffuse=(0.78, 0.55, 0.16), metallic=0.4, rough=0.35,
              specular=0.7, project_uvw=False),
        motor=P("motor", diffuse=(0.10, 0.10, 0.11), metallic=0.3, rough=0.45,
                specular=0.55, project_uvw=False),
        heatsink=P("heatsink",
                   diffuse_tex=tex["alu"]["diffuse"],
                   rough_tex=tex["alu"]["rough"],
                   normal_tex=tex["alu"]["normal"],
                   metallic=1.0, rough=0.30, specular=0.85, tex_scale=8.0),
        pill=P("pill", diffuse_tex=tex["pill"]["diffuse"],
               rough_tex=tex["pill"]["rough"],
               rough=0.42, specular=0.45, tex_scale=2.0),
        pill_red=P("pill_red", diffuse=(0.78, 0.22, 0.18), rough=0.35,
                   specular=0.55, project_uvw=False),
        pill_blue=P("pill_blue", diffuse=(0.22, 0.38, 0.72), rough=0.35,
                    specular=0.55, project_uvw=False),
        pill_yellow=P("pill_yellow", diffuse=(0.92, 0.78, 0.18), rough=0.35,
                      specular=0.55, project_uvw=False),
        screen=P("screen", diffuse=(0.01, 0.02, 0.015), metallic=0.0,
                 rough=0.06, specular=0.95,
                 emissive=(0.05, 0.42, 0.25), emit=180.0, project_uvw=False),
    )


# ── cyclorama (curved studio sweep so floor → wall has no hard edge) ───────

def build_cyclorama(stage, root, mat):
    """Curved studio sweep wrapping the line on ALL four sides. A flat floor
    centred on the origin gracefully rolls up into a tall vertical wall in
    every horizontal direction, so no matter where the camera looks the
    background is always polished concrete — never a hard-edged HDRI cut-out.
    Built as one large USD mesh."""
    inner_x = 12.0                    # half-width of the flat floor patch in X
    inner_y = 10.0                    # half-depth of the flat floor patch in Y
    curve_r = 3.4                     # curve radius (smooth horizon-less ramp)
    wall_h  = 10.0                    # vertical wall above the curve
    n_curve = 18
    n_wall  = 6

    # Build a 1-D radial profile (s, z): floor → quarter-circle → vertical wall
    profile = []
    # 1) flat run from rim outward by 0 (single point at the rim — interior is its own grid)
    profile.append((0.0, FLOOR_Z))
    # 2) quarter-circle curve up
    for i in range(1, n_curve + 1):
        a = (i / n_curve) * (math.pi / 2)
        s = curve_r * math.sin(a)
        z = FLOOR_Z + curve_r - curve_r * math.cos(a)
        profile.append((s, z))
    # 3) vertical wall
    for i in range(1, n_wall + 1):
        t = i / n_wall
        profile.append((curve_r, FLOOR_Z + curve_r + wall_h * t))

    # The cyclorama mesh = a flat floor rectangle EXTRUDED outward along each
    # of its four sides + corners by sweeping the profile around the rim.
    # We tessellate by walking the rim with parameter t ∈ [0, 1) and at each
    # rim point following the profile outward.
    nrim = 96                         # tessellation along the rim (full perimeter)

    def rim_point(t):
        """Return (rim_x, rim_y, outward_x, outward_y) at perimeter param t ∈ [0,1)."""
        # Round-corner rectangle: 4 straight sides + 4 quarter-arcs.
        corner_r = 1.5  # corner radius
        sx, sy = inner_x - corner_r, inner_y - corner_r
        side_x = 2 * sx
        side_y = 2 * sy
        arc = 0.5 * math.pi * corner_r
        perim = 2 * side_x + 2 * side_y + 4 * arc
        d = t * perim
        # bottom edge (+x), corner (+x,+y), right edge (+y), corner (-x,+y), top edge (-x), corner (-x,-y), left edge (-y), corner (+x,-y)
        if d < side_x:
            u = d / side_x
            return (-sx + u * 2 * sx, -inner_y, 0.0, -1.0)
        d -= side_x
        if d < arc:
            a = (d / arc) * (math.pi / 2)
            return (sx + corner_r * math.sin(a), -sy - corner_r * math.cos(a),
                    math.sin(a), -math.cos(a))
        d -= arc
        if d < side_y:
            u = d / side_y
            return (inner_x, -sy + u * 2 * sy, 1.0, 0.0)
        d -= side_y
        if d < arc:
            a = (d / arc) * (math.pi / 2)
            return (sx + corner_r * math.cos(a), sy + corner_r * math.sin(a),
                    math.cos(a), math.sin(a))
        d -= arc
        if d < side_x:
            u = d / side_x
            return (sx - u * 2 * sx, inner_y, 0.0, 1.0)
        d -= side_x
        if d < arc:
            a = (d / arc) * (math.pi / 2)
            return (-sx - corner_r * math.sin(a), sy + corner_r * math.cos(a),
                    -math.sin(a), math.cos(a))
        d -= arc
        if d < side_y:
            u = d / side_y
            return (-inner_x, sy - u * 2 * sy, -1.0, 0.0)
        d -= side_y
        # final corner
        a = (d / arc) * (math.pi / 2)
        return (-sx - corner_r * math.cos(a), -sy - corner_r * math.sin(a),
                -math.cos(a), -math.sin(a))

    pts = []
    sts = []
    # First strip: the interior flat floor (single quad with corners).
    # Build a coarse interior grid so it stays one mesh.
    nx_in, ny_in = 8, 8
    for j in range(ny_in + 1):
        v = j / ny_in
        y = -inner_y + 2 * inner_y * v
        for i in range(nx_in + 1):
            u = i / nx_in
            x = -inner_x + 2 * inner_x * u
            pts.append((x, y, FLOOR_Z))
            sts.append((u * 4, v * 4))

    floor_count = (nx_in + 1) * (ny_in + 1)
    idxs = []
    counts = []
    for j in range(ny_in):
        for i in range(nx_in):
            a = j * (nx_in + 1) + i
            b = a + 1
            d = a + (nx_in + 1)
            e = d + 1
            idxs.extend([a, b, e, d])
            counts.append(4)

    # Second mesh section: extruded rim — for each rim sample, build a ring
    # of vertices following the profile outward and upward.
    for k in range(nrim + 1):
        t = (k % nrim) / nrim
        rx, ry, ox, oy = rim_point(t)
        for pi, (s, pz) in enumerate(profile):
            x = rx + ox * s
            y = ry + oy * s
            pts.append((x, y, pz))
            sts.append((t * 16.0, pi / max(len(profile) - 1, 1) * 6.0))

    ring_size = len(profile)
    for k in range(nrim):
        for pi in range(ring_size - 1):
            a = floor_count + k * ring_size + pi
            b = a + 1
            d = floor_count + ((k + 1) % (nrim + 1)) * ring_size + pi
            e = d + 1
            idxs.extend([a, d, e, b])
            counts.append(4)

    _mesh(stage, f"{root}/cyclorama", pts, idxs, counts, mat, st=sts)


# ── conveyor: T-slot extrusion frame + rollers + drive + curved belt ───────

def _tslot_beam(stage, path, length, mat, *, pos, axis="X"):
    """40x40 mm aluminium-extrusion approximation: a square box with the
    brushed-aluminium PBR (the actual T-slot detail is below render scale)."""
    if axis == "X":
        dims = (length, 0.040, 0.040)
    elif axis == "Y":
        dims = (0.040, length, 0.040)
    else:
        dims = (0.040, 0.040, length)
    _box(stage, path, dims, pos, mat)


def _belt_loop(stage, path, mat):
    """One closed mesh that wraps the belt around both end rollers.

    The belt is a thin shell of constant thickness `t` whose centreline is
    offset `t/2` outward from the loop. The cross-section is a Y-direction
    extrusion (belt width)."""
    t = S.BELT_THICK
    r_in = ROLLER_R                    # belt's inner surface tangent to roller
    r_out = ROLLER_R + t               # outer
    n_run = 36
    n_wrap = 14
    cy_l = -HX                         # tail roller centre x
    cy_r = +HX                         # head roller centre x
    cz = BELT_TOP - r_in               # roller centres are r_in below BELT_TOP

    def pts_along(r):
        """List of (x, z) along the *centreline* offset (r=r_in inner, r_out outer)."""
        line = []
        # top run, left → right (inner edge at BELT_TOP, outer at BELT_TOP + t)
        for i in range(n_run + 1):
            x = cy_l + (cy_r - cy_l) * i / n_run
            line.append((x, cz + r))
        # head wrap, right end, top→bottom (θ from 0 to π)
        for i in range(1, n_wrap + 1):
            a = math.pi * i / n_wrap
            line.append((cy_r + r * math.sin(a), cz + r * math.cos(a)))
        # bottom run, right → left
        for i in range(1, n_run + 1):
            x = cy_r + (cy_l - cy_r) * i / n_run
            line.append((x, cz - r))
        # tail wrap, left end, bottom→top
        for i in range(1, n_wrap):
            a = math.pi * i / n_wrap
            line.append((cy_l - r * math.sin(a), cz - r * math.cos(a)))
        return line

    inner = pts_along(r_in)
    outer = pts_along(r_out)
    nloop = len(inner)

    pts = []
    for (xi, zi), (xo, zo) in zip(inner, outer):
        # +Y and -Y sides of belt width
        pts.append((xi, +HY, zi))
        pts.append((xi, -HY, zi))
        pts.append((xo, +HY, zo))
        pts.append((xo, -HY, zo))
    sts = []
    # simple UVs from path index (u tracks length, v tracks width)
    for i in range(nloop):
        u = i / max(nloop - 1, 1) * 6.0
        sts.append((u, 0.0))
        sts.append((u, 1.0))
        sts.append((u, 0.0))
        sts.append((u, 1.0))

    idxs = []
    counts = []

    def quad(a, b, c, d):
        idxs.extend([a, b, c, d])
        counts.append(4)

    for i in range(nloop):
        j = (i + 1) % nloop
        a0, a1, a2, a3 = i * 4, i * 4 + 1, i * 4 + 2, i * 4 + 3
        b0, b1, b2, b3 = j * 4, j * 4 + 1, j * 4 + 2, j * 4 + 3
        # outer surface (the visible belt skin)
        quad(a2, b2, b3, a3)
        # inner surface
        quad(a1, b1, b0, a0)
        # +Y side edge
        quad(a0, b0, b2, a2)
        # -Y side edge
        quad(a3, b3, b1, a1)

    _mesh(stage, path, pts, idxs, counts, mat, st=sts)


def build_conveyor(stage, root, M):
    UsdGeom.Xform.Define(stage, f"{root}/conveyor")

    # ── frame: 40 mm T-slot extrusion ──
    # longitudinal beams under the belt, one per side, plus a centre support
    for sy in (-1, 1):
        _tslot_beam(stage, f"{root}/conveyor/long_{'p' if sy>0 else 'n'}",
                    BELT_LEN + 0.10, M["alu"],
                    pos=(0, sy * (HY + 0.022), BELT_TOP - 0.060), axis="X")
    # cross-braces between the longitudinals
    for x in (-HX + 0.10, 0.0, HX - 0.10):
        _tslot_beam(stage, f"{root}/conveyor/cross_{x:+.2f}".replace(".", "_").replace("+", "p").replace("-", "n"),
                    S.BELT_WIDTH + 0.05, M["alu"],
                    pos=(x, 0.0, BELT_TOP - 0.060), axis="Y")
    # vertical legs + foot pads
    legh = (BELT_TOP - 0.060 - 0.020) - FLOOR_Z       # to top of foot pad
    for sx in (-1, 1):
        for sy in (-1, 1):
            lx = sx * (HX - 0.12)
            ly = sy * (HY + 0.022)
            tag = f"{'p' if sx>0 else 'n'}_{'p' if sy>0 else 'n'}"
            _tslot_beam(stage, f"{root}/conveyor/leg_{tag}",
                        legh, M["alu"], pos=(lx, ly, FLOOR_Z + legh / 2), axis="Z")
            _cyl(stage, f"{root}/conveyor/foot_{tag}", 0.030, 0.010,
                 (lx, ly, FLOOR_Z + 0.005), M["steel"])

    # ── rollers + bearing housings + drive ──
    for sx, name in ((-1, "tail"), (+1, "head")):
        cx = sx * HX
        cz = BELT_TOP - ROLLER_R
        # main roller drum
        _cyl(stage, f"{root}/conveyor/roller_{name}", ROLLER_R, S.BELT_WIDTH,
             (cx, 0.0, cz), M["steel"], axis="Y")
        # roller end caps (slightly larger discs)
        for sy in (-1, 1):
            _cyl(stage, f"{root}/conveyor/cap_{name}_{'p' if sy>0 else 'n'}",
                 ROLLER_R * 1.02, 0.004,
                 (cx, sy * (S.BELT_WIDTH / 2 + 0.003), cz), M["steel"], axis="Y")
            # bearing housing — a black pillow block bolted on the side
            _box(stage, f"{root}/conveyor/bearing_{name}_{'p' if sy>0 else 'n'}",
                 (0.060, 0.022, 0.075),
                 (cx, sy * (HY + 0.024), cz), M["motor"])
        # drive motor + gearbox on the head roller, behind +Y side
        if name == "head":
            mx = cx + 0.005
            my = HY + 0.072
            mz = cz
            # gearbox block
            _box(stage, f"{root}/conveyor/gearbox", (0.080, 0.060, 0.080),
                 (mx, my, mz), M["motor"])
            # motor body
            _cyl(stage, f"{root}/conveyor/motor", 0.038, 0.110,
                 (mx, my + 0.085, mz), M["motor"], axis="Y")
            # cooling fins on the motor body
            for i in range(7):
                fy = my + 0.035 + i * 0.012
                _cyl(stage, f"{root}/conveyor/fin_{i}", 0.040, 0.002,
                     (mx, fy, mz), M["alu"], axis="Y")

    # ── side guide rails ──
    rail_h = 0.045
    for sy in (-1, 1):
        _box(stage, f"{root}/conveyor/rail_{'p' if sy>0 else 'n'}",
             (BELT_LEN, 0.008, rail_h),
             (0.0, sy * (HY + 0.004), BELT_TOP + rail_h / 2), M["alu"])

    # ── the belt itself ──
    _belt_loop(stage, f"{root}/conveyor/belt", M["belt"])


# ── tactile mesh + scanner PCB ─────────────────────────────────────────────

def build_mesh_sensor(stage, root, M):
    UsdGeom.Xform.Define(stage, f"{root}/sensor")
    # Subdivided Velostat strip running the whole belt length (every part inspected).
    nu, nv = 60, 12
    pts = []
    sts = []
    for j in range(nv + 1):
        v = j / nv
        for i in range(nu + 1):
            u = i / nu
            x = -BELT_LEN / 2 + BELT_LEN * u
            y = -MESH_BELT_W / 2 + MESH_BELT_W * v
            pts.append((x, y, -S.MESH_THICK / 2))
            sts.append((u * 24.0, v * 3.0))
    idxs = []
    counts = []
    for j in range(nv):
        for i in range(nu):
            a = j * (nu + 1) + i
            b = a + 1
            c = a + (nu + 1)
            d = c + 1
            idxs.extend([a, b, d, c])
            counts.append(4)
    _mesh(stage, f"{root}/sensor/mat_top", pts, idxs, counts, M["velostat"], st=sts)
    # mat bottom face (just enough thickness to read)
    _box(stage, f"{root}/sensor/mat_bot", (BELT_LEN, MESH_BELT_W, S.MESH_THICK),
         (0, 0, -S.MESH_THICK / 2 - 0.0001), M["velostat"])

    # 10 mm sensor-cell grid — very thin, very dark lines printed on the mat.
    # Anything thicker reads as "green graph paper" and kills the fabric look.
    cell = S.CELL_PITCH
    UsdGeom.Xform.Define(stage, f"{root}/sensor/grid")
    ny = int(round(MESH_BELT_W / cell))
    for j in range(ny + 1):
        y = -MESH_BELT_W / 2 + j * cell
        _box(stage, f"{root}/sensor/grid/lx_{j}",
             (BELT_LEN, 0.00040, 0.00020),
             (0, y, 0.00012), M["cell"])
    nx = int(round(BELT_LEN / cell))
    for i in range(nx + 1):
        x = -BELT_LEN / 2 + i * cell
        _box(stage, f"{root}/sensor/grid/ly_{i}",
             (0.00040, MESH_BELT_W, 0.00020),
             (x, 0, 0.00012), M["cell"])


def build_scanner_pcb(stage, root, M):
    """Scanner PCB tucked just outside the mat on the +Y rail edge."""
    UsdGeom.Xform.Define(stage, f"{root}/scanner")
    # The board sits just outside the mat on the +Y rail
    px = 0.0
    py = HY - 0.080
    pz = BELT_TOP + 0.001
    _box(stage, f"{root}/scanner/pcb", (0.090, 0.060, 0.0016),
         (px, py, pz + 0.0008), M["pcb"])
    # STM32 main MCU (QFP) — small dark square in the centre
    _box(stage, f"{root}/scanner/ic_mcu", (0.012, 0.012, 0.0018),
         (px - 0.018, py, pz + 0.0025), M["chip"])
    # 4× analog mux ICs in a row
    for i, dx in enumerate((-0.005, 0.008, 0.021, 0.034)):
        _box(stage, f"{root}/scanner/ic_mux_{i}", (0.006, 0.010, 0.0014),
             (px + dx, py - 0.018, pz + 0.0022), M["chip"])
    # FFC connector + USB-C
    _box(stage, f"{root}/scanner/conn_ffc", (0.034, 0.006, 0.0030),
         (px, py + 0.025, pz + 0.0025), M["conn"])
    _box(stage, f"{root}/scanner/conn_usb", (0.009, 0.007, 0.0035),
         (px - 0.040, py, pz + 0.0026), M["conn"])

    # FFC ribbon — single curved strip mesh from the mat edge over the rail
    # up to the scanner connector. Smooth bow, no brick-stack artefacts.
    nv = 24
    ribbon_w = 0.030
    y0 = MESH_BELT_W / 2 - 0.001
    y1 = py + 0.022
    z0 = 0.00045
    z1 = pz + 0.0028
    pts = []
    sts = []
    for k in range(nv + 1):
        t = k / nv
        y = y0 + (y1 - y0) * t
        z = z0 + (z1 - z0) * t + 0.018 * math.sin(math.pi * t)
        # left and right edges of the ribbon, centred on px
        pts.append((px - ribbon_w / 2, y, z))
        pts.append((px + ribbon_w / 2, y, z))
        sts.append((0.0, t * 4.0))
        sts.append((1.0, t * 4.0))
    idxs = []
    counts = []
    for k in range(nv):
        a, b = k * 2, k * 2 + 1
        c, d = (k + 1) * 2, (k + 1) * 2 + 1
        idxs.extend([a, c, d, b])
        counts.append(4)
    _mesh(stage, f"{root}/scanner/ffc_ribbon", pts, idxs, counts, M["ffc"], st=sts)


# ── pills ──────────────────────────────────────────────────────────────────

def build_pills(stage, root, M):
    UsdGeom.Xform.Define(stage, f"{root}/pills")
    rng = np.random.default_rng(11)
    spacing = 0.036
    idx = 0
    for cx in (-0.85, -0.40, 0.05, 0.50, 0.95):
        n = 3
        o = -(n - 1) * spacing / 2
        for i in range(n):
            for k in range(n):
                x, y = cx + o + i * spacing, o + k * spacing
                idx += 1
                roll = rng.random()
                if roll < 0.18:
                    mat = M["pill_red"]
                elif roll < 0.30:
                    mat = M["pill_blue"]
                elif roll < 0.40:
                    mat = M["pill_yellow"]
                else:
                    mat = M["pill"]
                if rng.random() < 0.45:
                    _capsule(stage, f"{root}/pills/p_{idx}", 0.005, 0.012,
                             (x, y, 0.0055), mat, axis="X")
                else:
                    _sphere(stage, f"{root}/pills/p_{idx}", 0.013,
                            (x, y, 0.0035), mat, scale=(1.0, 1.0, 0.30))
    # scatter along the rest of the belt so the line reads continuous
    for _ in range(14):
        x = rng.uniform(-HX + 0.1, HX - 0.1)
        y = rng.uniform(-0.10, 0.10)
        idx += 1
        _sphere(stage, f"{root}/pills/p_{idx}", 0.013, (x, y, 0.0035),
                M["pill"], scale=(1.0, 1.0, 0.30))


# ── kiosk: import the printed body+bezel from the .scad ────────────────────

def _ensure_enclosure_stl():
    body = os.path.join(ASSETS, "edge_body.stl")
    bezel = os.path.join(ASSETS, "edge_bezel.stl")
    scad = os.path.join(REPO, "hardware", "edge_enclosure", "edge_enclosure.scad")
    osc = os.environ.get("OPENSCAD") or shutil.which("openscad")
    if not osc:
        raise RuntimeError(
            "OpenSCAD not found — required to export the edge enclosure STL from "
            f"{scad}. Install via `apt-get install -y openscad`, or pre-render "
            f"the STLs into {ASSETS}/")
    for part, dst in (("body", body), ("bezel", bezel)):
        if not os.path.exists(dst):
            subprocess.run([osc, "-o", dst, "-D", f'part="{part}"', scad], check=True)
    return body, bezel


def _read_stl_smooth(path):
    """Read STL, weld coincident vertices, compute averaged smooth normals.
    Returns (points, indices, normals)."""
    with open(path, "rb") as f:
        head = f.read(5)
    tris = []
    if head == b"solid":
        with open(path, "r", errors="ignore") as f:
            verts = []
            for line in f:
                s = line.strip()
                if s.startswith("vertex"):
                    _, x, y, z = s.split()
                    verts.append((float(x), float(y), float(z)))
                    if len(verts) == 3:
                        tris.append(verts)
                        verts = []
    else:
        with open(path, "rb") as f:
            f.read(80)
            (n,) = struct.unpack("<I", f.read(4))
            for _ in range(n):
                f.read(12)
                tri = []
                for _ in range(3):
                    tri.append(struct.unpack("<3f", f.read(12)))
                tris.append(tri)
                f.read(2)
    # weld
    table = {}
    points = []

    def key(v):
        return (round(v[0], 5), round(v[1], 5), round(v[2], 5))
    idx = []
    for tri in tris:
        for v in tri:
            k = key(v)
            if k not in table:
                table[k] = len(points)
                points.append(v)
            idx.append(table[k])
    pts = np.asarray(points, dtype=np.float32)
    inds = np.asarray(idx, dtype=np.int32).reshape(-1, 3)
    # smooth vertex normals (area-weighted)
    n = np.zeros_like(pts)
    v0 = pts[inds[:, 0]]
    v1 = pts[inds[:, 1]]
    v2 = pts[inds[:, 2]]
    face_n = np.cross(v1 - v0, v2 - v0)
    np.add.at(n, inds[:, 0], face_n)
    np.add.at(n, inds[:, 1], face_n)
    np.add.at(n, inds[:, 2], face_n)
    lens = np.linalg.norm(n, axis=1, keepdims=True)
    lens[lens < 1e-12] = 1.0
    n = n / lens
    return pts, inds.reshape(-1), n


def _stl_mesh(stage, path, stl_path, mat, *, pos, scale, euler=None):
    pts, idx, nrm = _read_stl_smooth(stl_path)
    counts = [3] * (len(idx) // 3)
    _mesh(stage, path, pts, idx.tolist(), counts, mat,
          pos=pos, euler=euler, scale=(scale, scale, scale),
          normals=nrm.tolist())


def build_jetson(stage, base, M):
    UsdGeom.Xform.Define(stage, base)
    _box(stage, f"{base}/carrier", (S.JETSON_W, S.JETSON_D, 0.0016),
         (0, 0, 0.0008), M["pcb"])
    hs_w = 0.072
    _box(stage, f"{base}/hs_base", (hs_w, hs_w, 0.006),
         (0, 0, 0.004), M["heatsink"])
    nfin = 14
    for i in range(nfin):
        fy = -hs_w / 2 + (i + 0.5) * hs_w / nfin
        _box(stage, f"{base}/fin_{i}", (hs_w, hs_w / nfin * 0.45, 0.022),
             (0, fy, 0.018), M["heatsink"])
    # fan over the heatsink
    _cyl(stage, f"{base}/fan", hs_w / 2 * 0.85, 0.008,
         (0, 0, 0.031), M["chip"])
    # GPIO header
    _box(stage, f"{base}/gpio", (0.0025, 0.0505, 0.006),
         (S.JETSON_W / 2 - 0.006, 0, 0.005), M["chip"])


def build_edge_appliance(stage, root, M):
    UsdGeom.Xform.Define(stage, f"{root}/edgebox")
    # kiosk on a VESA stand beside the belt, downstream
    bx, by = 0.50, -(HY + 0.20)
    # height of device CENTRE above the floor
    cz = BELT_TOP + 0.22
    # stand base + tilted post
    _box(stage, f"{root}/edgebox/stand_base", (0.20, 0.16, 0.014),
         (bx, by, FLOOR_Z + 0.007), M["alu"])
    post_h = cz - FLOOR_Z - 0.007
    _box(stage, f"{root}/edgebox/stand_post", (0.045, 0.045, post_h),
         (bx, by + 0.03, FLOOR_Z + 0.007 + post_h / 2), M["alu"])

    # parent Xform = kiosk pose. The STL is xy-centred with depth 0..64mm in +z;
    # we centre z too (local -0.032) so the device rotates about its centre.
    app = UsdGeom.Xform.Define(stage, f"{root}/edgebox/appliance")
    # euler X=80° stands the screen up to face the operator (-Y), tilted back
    _xform(app.GetPrim(), pos=(bx, by, cz), euler=(80.0, 0.0, 0.0))
    base = f"{root}/edgebox/appliance"
    half_d = 0.032                                # half the 64 mm device depth

    body_stl, bezel_stl = _ensure_enclosure_stl()
    _stl_mesh(stage, f"{base}/body", body_stl, M["graphite"],
              pos=(0, 0, -half_d), scale=0.001)
    _stl_mesh(stage, f"{base}/bezel", bezel_stl, M["alu"],
              pos=(0, 0, half_d), scale=0.001)
    build_jetson(stage, f"{base}/jetson", M)
    _xform(stage.GetPrimAtPath(f"{base}/jetson"),
           pos=(0, 0, -half_d + 0.012))

    # recessed emissive display, slightly smaller than the bezel window
    scr_z = half_d - 0.001
    _box(stage, f"{base}/screen",
         (S.DISP_ACT_W * 0.97, S.DISP_ACT_H * 0.97, 0.0015),
         (0, 0, scr_z), M["screen"])


# ── scene assembly ─────────────────────────────────────────────────────────

def build(stage):
    root = "/World"
    UsdGeom.Xform.Define(stage, root)
    UsdGeom.Xform.Define(stage, root + "/M")
    tex = TEX.ensure_all()
    M = build_materials(stage, root, tex)

    build_cyclorama(stage, root, M["concrete"])
    build_conveyor(stage, root, M)
    build_mesh_sensor(stage, root, M)
    build_scanner_pcb(stage, root, M)
    build_pills(stage, root, M)
    build_edge_appliance(stage, root, M)


# ── lights ─────────────────────────────────────────────────────────────────

HDRI = os.environ.get("SCENE_HDRI", "/workspace/hdri.hdr")


def setup_lighting(stage):
    UsdGeom.Xform.Define(stage, "/World/Lights")
    dome = UsdLux.DomeLight.Define(stage, "/World/Lights/dome")
    dome.CreateIntensityAttr(900.0)
    if HDRI and os.path.exists(HDRI):
        dome.CreateTextureFileAttr(HDRI)
        dome.CreateTextureFormatAttr("latlong")
    else:
        fallback = TEX.studio_dome_hdr()
        dome.CreateTextureFileAttr(fallback)
        dome.CreateTextureFormatAttr("latlong")
    _xform(dome.GetPrim(), euler=(90, 0, -25))

    # warm key from front-camera-right
    key = UsdLux.DistantLight.Define(stage, "/World/Lights/key")
    key.CreateIntensityAttr(1900.0)
    key.CreateColorAttr(Gf.Vec3f(1.0, 0.96, 0.88))
    key.CreateAngleAttr(1.2)
    _xform(key.GetPrim(), euler=(-44, 18, 28))

    # cool rim from behind to catch chamfers and bezel
    rim = UsdLux.DistantLight.Define(stage, "/World/Lights/rim")
    rim.CreateIntensityAttr(2400.0)
    rim.CreateColorAttr(Gf.Vec3f(0.7, 0.82, 1.0))
    rim.CreateAngleAttr(0.8)
    _xform(rim.GetPrim(), euler=(-30, 195, -10))

    # soft overhead fill (factory ceiling diffuser)
    rect = UsdLux.RectLight.Define(stage, "/World/Lights/overhead")
    rect.CreateIntensityAttr(5800.0)
    rect.CreateWidthAttr(2.0)
    rect.CreateHeightAttr(1.0)
    rect.CreateColorAttr(Gf.Vec3f(0.97, 0.98, 1.0))
    _xform(rect.GetPrim(), pos=(0.0, -0.05, 1.4), euler=(0, 0, 0))

    # a small accent for the kiosk so the bezel reads even when the screen is dim
    acc = UsdLux.RectLight.Define(stage, "/World/Lights/kiosk_accent")
    acc.CreateIntensityAttr(2200.0)
    acc.CreateWidthAttr(0.5)
    acc.CreateHeightAttr(0.4)
    acc.CreateColorAttr(Gf.Vec3f(0.95, 0.97, 1.0))
    _xform(acc.GetPrim(), pos=(0.55, -0.55, 0.30), euler=(-20, 0, 0))


# ── cameras + headless RTX capture ─────────────────────────────────────────

VIEWS = {
    "twin_scene":    ((0.70, -0.80, 0.42), (0.05, -0.05, 0.0), 27.0),
    "twin_overview": ((1.70, -1.55, 1.15), (0.00, 0.00, -0.03), 17.0),
    "twin_line":     ((-1.35, -0.60, 0.42), (0.35, 0.0, 0.0), 22.0),
}


def _set_path_traced():
    """Switch the RTX render mode to path-traced where available, so the
    final hero shots get proper indirect light + reflections."""
    try:
        rep.settings.set_render_pathtraced(samples_per_pixel_per_subframe=64)
    except Exception:
        # older Replicator builds expose only individual carb settings
        try:
            import carb
            cs = carb.settings.get_settings()
            cs.set("/rtx/rendermode", "PathTracing")
            cs.set("/rtx/pathtracing/spp", 32)
            cs.set("/rtx/pathtracing/totalSpp", 1024)
            cs.set("/rtx/pathtracing/maxBounces", 6)
        except Exception:
            pass


def render(steps=220):
    from isaacsim.core.api import World
    world = World(stage_units_in_meters=1.0)
    stage = world.stage
    build(stage)
    setup_lighting(stage)
    world.reset()

    _set_path_traced()

    products = {}
    for name, (pos, look, fl) in VIEWS.items():
        cam = rep.create.camera(position=pos, look_at=look, focal_length=fl)
        rp = rep.create.render_product(cam, (_W, _H))
        ann = rep.AnnotatorRegistry.get_annotator("rgb")
        ann.attach(rp)
        products[name] = ann

    for _ in range(steps):
        world.step(render=True)

    for name, ann in products.items():
        img = np.asarray(ann.get_data())[..., :3].astype(np.uint8)
        path = os.path.join(OUT, f"{name}.png")
        Image.fromarray(img).save(path)
        print(f"[scene] rendered -> {path}  shape={img.shape}  mean={img.mean():.1f}")


if __name__ == "__main__":
    render()
    sim_app.close()
    print("[scene] OK")
