"""Aggregate every analysis module's findings into a single Markdown report
and a JSON sidecar for machine consumption (e.g. GitHub Actions annotations).
"""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path

from .findings import Finding, banner


REPORT_HEADER = """# Conet Scanner v1 — PCB Reality Check

> Generated by `tools/reality_check` on {ts}.
>
> This report answers the question: **"If we send `gerbers.zip` + `bom.csv` + `cpl.csv` to
> JLCPCB as-is, what is the realistic probability that the boards come back working,
> versus DOA, smoking, or measurement-quality-broken?"**
>
> Source of truth for each finding:
> * BOM    — [`hardware/pcb/conet-scanner-v1/bom.csv`](../bom.csv)
> * CPL    — [`hardware/pcb/conet-scanner-v1/cpl.csv`](../cpl.csv)
> * Gerber — [`hardware/pcb/conet-scanner-v1/gerbers.zip`](../gerbers.zip)
> * Schematic — [`hardware/pcb/conet-scanner-v1/schematic.md`](../schematic.md)

## Verdict

{verdict}

## Burn-risk severity legend

| Level | Name | Meaning |
|------:|:-----|:--------|
| 5 | FIRE     | Visible smoke / fire on first power-up, or assembler outright rejects the order. |
| 4 | CRITICAL | Board boots but cannot complete its primary function (no WiFi, brownout loop, measurement saturates). |
| 3 | MAJOR    | Functional with significant degradation (lower yield, reduced range, manual rework needed). |
| 2 | WARNING  | Works but with caveats; calibration or firmware tweak hides the symptom. |
| 1 | ADVISORY | Cosmetic / good-to-know; first-article inspection should look at it. |
| 0 | INFO     | Documented for traceability; no action. |

"""


def _section(title: str, findings: list[Finding]) -> str:
    if not findings:
        return f"## {title}\n\n_No findings._\n\n"
    by_sev = sorted(findings, key=lambda f: -f.severity)
    out = [f"## {title}", ""]
    out.append(f"_{len(findings)} finding(s)._")
    out.append("")
    for f in by_sev:
        out.append(f"### [{banner(f.severity)}] `{f.code}` — {f.title}")
        out.append("")
        if f.refs:
            out.append(f"**Refs:** {', '.join('`' + r + '`' for r in f.refs)}")
            out.append("")
        out.append(f.detail.strip())
        out.append("")
    return "\n".join(out) + "\n"


def _compute_verdict(all_findings: list[Finding]) -> str:
    sev_counts = {i: 0 for i in range(6)}
    for f in all_findings:
        sev_counts[f.severity] += 1
    lines: list[str] = []
    if sev_counts[5] or sev_counts[4]:
        lines.append("**🛑 DO NOT ORDER YET.**")
        lines.append("")
        lines.append(
            f"Found **{sev_counts[5]}** FIRE-level and **{sev_counts[4]}** CRITICAL "
            "issues. The next reality-check pass on this branch should resolve all "
            "FIRE-level findings before any money goes to JLCPCB."
        )
    elif sev_counts[3]:
        lines.append("**⚠️  Borderline. Order if you accept a v1 with caveats.**")
        lines.append("")
        lines.append(
            f"No fire-level issues, but **{sev_counts[3]}** MAJOR issues need manual "
            "review on the first article."
        )
    else:
        lines.append("**✅ Reality check passes. Safe to send to JLCPCB.**")
    lines.append("")
    lines.append("Severity counts:")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---------:|------:|")
    for i in range(5, -1, -1):
        lines.append(f"| {banner(i)} ({i}) | {sev_counts[i]} |")
    return "\n".join(lines)


def build(
    bom_findings: list[Finding],
    cpl_findings: list[Finding],
    gerber_findings: list[Finding],
    power_findings: list[Finding],
    strap_findings: list[Finding],
    adc_findings: list[Finding],
    topo_findings: list[Finding],
    sim_findings: list[Finding],
    sim_runs: list[dict],
    power_table: list[dict],
    adc_table: list[dict],
    gerber_summary: dict,
    out_md: Path,
    out_json: Path,
) -> None:
    all_findings = (
        bom_findings + cpl_findings + gerber_findings
        + power_findings + strap_findings + adc_findings
        + topo_findings + sim_findings
    )
    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    verdict = _compute_verdict(all_findings)

    body = [REPORT_HEADER.format(ts=ts, verdict=verdict)]

    body.append(_section("1. BOM cross-check (`bom.csv`)", bom_findings))
    body.append(_section("2. Placement cross-check (`cpl.csv`)", cpl_findings))
    body.append(_section("3. Gerber inspection (`gerbers.zip`)", gerber_findings))
    body.append(_section("4. Power budget under Shenzhen reality", power_findings))
    body.append(_section("5. ESP32-S3 strapping / boot integrity", strap_findings))
    body.append(_section("6. ADC divider & measurement range", adc_findings))
    body.append(_section("7. Schematic vs Wokwi vs Firmware topology", topo_findings))
    body.append(_section("8. Reality-adjusted software-mode simulation", sim_findings))

    # Software-sim run table
    if sim_runs:
        body.append("### Software-sim run results\n")
        keys = list(sim_runs[0].keys())
        body.append("| " + " | ".join(keys) + " |")
        body.append("|" + "|".join("---" for _ in keys) + "|")
        for r in sim_runs:
            body.append("| " + " | ".join(str(r[k]) for k in keys) + " |")
        body.append("")

    # Appendix: power table
    body.append("## Appendix A — Power budget table\n")
    if power_table:
        keys = list(power_table[0].keys())
        body.append("| " + " | ".join(keys) + " |")
        body.append("|" + "|".join("---" for _ in keys) + "|")
        for row in power_table:
            body.append("| " + " | ".join(str(row[k]) for k in keys) + " |")
        body.append("")

    body.append("## Appendix B — ADC divider sweep\n")
    if adc_table:
        keys = list(adc_table[0].keys())
        body.append("| " + " | ".join(keys) + " |")
        body.append("|" + "|".join("---" for _ in keys) + "|")
        for row in adc_table:
            body.append("| " + " | ".join(str(row[k]) for k in keys) + " |")
        body.append("")

    body.append("## Appendix C — Gerber layer stats\n")
    body.append("| File | Bytes | n_traces | n_apertures | min_aperture_um | bbox |")
    body.append("|---|---|---|---|---|---|")
    for L in gerber_summary.get("layers", []):
        ap = "n/a" if L["min_aperture_mm"] in (None, float("inf")) else f"{L['min_aperture_mm']*1000:.1f}"
        bbox = "n/a" if not L["bbox"] else f"({L['bbox'][0]:.1f},{L['bbox'][1]:.1f})-({L['bbox'][2]:.1f},{L['bbox'][3]:.1f})"
        body.append(f"| `{L['name']}` | {L['bytes']} | {L['n_traces']} | {L['n_apertures']} | {ap} | {bbox} |")
    body.append("")
    body.append("Drill files:\n")
    body.append("| File | Bytes | hits | n_tools | min_drill_mm |")
    body.append("|---|---|---|---|---|")
    for D in gerber_summary.get("drills", []):
        md = "n/a" if D["min_drill_mm"] in (None, float("inf")) else f"{D['min_drill_mm']:.3f}"
        body.append(f"| `{D['name']}` | {D['bytes']} | {D['hits']} | {D['n_tools']} | {md} |")
    body.append("")

    out_md.write_text("\n".join(body), encoding="utf-8")

    out_json.write_text(json.dumps({
        "generated_at": ts,
        "verdict": verdict,
        "findings": [asdict(f) for f in all_findings],
        "power_table": power_table,
        "adc_table": adc_table,
        "gerber_summary": gerber_summary,
    }, indent=2, default=str), encoding="utf-8")
